name: aoc2020
version: 0.1.0.0
github: z0isch/aoc2020
license: BSD3
author: AJ Ruf
maintainer: z0isch@gmail.com
copyright: 2020 AJ Ruf

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/githubuser/aoc2020#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - generic-lens
  - lens
  - containers
  - megaparsec
  - linear
  - split

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc2020
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  aoc2020-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - aoc2020
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
